# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields
import smssync.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sent_from', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('message_id', models.CharField(max_length=32)),
                ('sent_to', models.CharField(blank=True, max_length=32)),
                ('device_id', models.CharField(blank=True, max_length=32)),
                ('sent_timestamp', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'ordering': ['-created'],
            },
            bases=(smssync.models.MessageBase, models.Model),
        ),
        migrations.CreateModel(
            name='OutgoingMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=160)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('to', phonenumber_field.modelfields.PhoneNumberField(editable=False, max_length=128)),
                ('sent', models.BooleanField(default=False, editable=False)),
                ('sent_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created'],
            },
            bases=(smssync.models.MessageBase, models.Model),
        ),
    ]
