# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smssync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='received',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='received_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
