# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smssync', '0002_add_received_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmessage',
            name='message_id',
        ),
    ]
